### PR TITLE
150 feedback

### PR DESCRIPTION
**Pull request by cubap**
My Netbeans is stuck in a loop right now, so this is awaiting some end-to-end testing, but I think we're in good shape. I want to see if the events are available in all the scopes I expect.

### CODE REVIEW

**Comment by thehabes** [comment]
Cool, I can always pull it down and deploy it to dev if you want it there.

**Comment by cubap** [comment]
I think we're set. It looks good on my machine, but we can push it up to dev

**Comment by thehabes** [comment]
Deployed to http://lived-religion-dev.rerum.io, will test a bit.

**Comment by thehabes** [comment]
When I use the ?id page to update (a location), it says "Saving `location name` successful", which is the same message as create.  Unless that is what you are going for.  I figured those actions would have separate messages.

**Comment by thehabes** [comment]
The icons appear in the message when deleting an item from a collection.

**Comment by cubap** [comment]
> When I use the ?id page to update (a location), it says "Saving `location name` successful", which is the same message as create. Unless that is what you are going for. I figured those actions would have separate messages.

That's right. The place where the events were injected does not always know about the type of request that is happening, so rather than reengineer what you have done already, I acknowledged that a user who updates and clicks on "Submit" will want to know it saved. Similarly, someone creating a new whatever, will be satisfied with a "Saved" notice.

**Comment by cubap** [comment]
This is "simple" feedback, but we may want to note here that failures are not very well communicated to the user yet.

**Comment by thehabes** [comment]
I am good with that, just making sure that's the functionality you intended.

**Comment by cubap** [comment]
> The icons appear in the message when deleting an item from a collection (happened on objects.html)

I love that. I hadn't caught it.

**Comment by thehabes** [comment]
Yeah that was happening right at the end of my sprint on that, and I thought I fixed it, but may not have.

**Comment by thehabes** [comment]
Too much or too few `parentElement` and `previousElementSibling` going on.  Not a huge fan of depending on HTMLElement order.

**Comment by thehabes** [comment]
Besides the Icon thing, I see no other errors.

**Comment by thehabes** [comment]
That did it!  I want this in my branch!

**Pull request merged**
